baseURL: "https://www.alexanderkriwoluzky.com/"
title: Alexander Kriwoluzky
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Working Papers
          url: working-papers/
          weight: 2
        - name: Publications
          url: publications/
          weight: 3
        - name: Writing for General Public
          url: writing/
          weight: 4
        - name: Teaching
          url: teaching/
          weight: 5

params:
    description: "This website hosts Alexander Kriwoluzky's research papers, publications, teaching materials, and contact information."
    author: Alexander Kriwoluzky
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["working-papers","publications","writing","teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          
          subtitle: "I am a professor at Freie Universität Berlin and head of macroeconomics department at the German Institute for Economic Research (DIW) Berlin. My research focuses on monetary policy, fiscal policy, and its interaction."
          imageUrl: "foto_webpage.jpg"
          imageWidth: 240
          imageHeight: 240
          buttons:
            - name: Working Papers
              url: working-papers/
            - name: Publications
              url: publications/
            - name: Teaching
              url: teaching/
            - name: Writing
              url: writing/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: CV.pdf
        - name: Email
          url: mailto:akriwoluzky@diw.de
        - name: Location
          url: location/
        - name: LinkedIn
          url: https://www.linkedin.com/in/alexander-kriwoluzky-b11331288/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alexander Kriwoluzky"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
